swagger: '2.0'
info:
  version: 1.0.0
  title: gatherme-requests-ms
  description: "Microservicio para Solicitudes\n 
    Python + SQLite"
  license:
    name: Proyecto Gatherme, Software Architecture, 2020-I
  
    
host: 0.0.0.0:4444
basePath: /<user>/gatherme-requests
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
  
  
paths:

  /create:
    post:
      summary: Crear una nueva solicitud de Gather
      operationId: create
      parameters:
        - name: usersJSON
          in: body
          required: true
          description: JSON con los usuarios de la solicitud
          schema:
            type: array
            items:
              $ref: "#/definitions/RequestInput"
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /sent:
    get:
      summary: Retorna las solicitudes enviadas por el usuario
      operationId: sent
      parameters:
        - name: userJSON
          in: body
          required: true
          description: JSON con el usuario que solicita
          schema:
            type: array
            items:
              $ref: "#/definitions/RequestGetInput"
      responses:
        '200':
          description: Ok
          schema:
            type: array
            items:
              $ref: "#/definitions/Request"
        '500':
          description: Internal Server Error
          
  /inbox:
    get:
      summary: Retorna las solicitudes recibidas por el usuario
      operationId: inbox
      parameters:
        - name: userJSON
          in: body
          required: true
          description: JSON con el usuario que solicita
          schema:
            type: array
            items:
              $ref: "#/definitions/RequestGetInput"
      responses:
        '200':
          description: Ok
          schema:
            type: array
            items:
              $ref: "#/definitions/Request"
        '500':
          description: Internal Server Error

  /accept:
    put:
      summary: Aceptar una solicitud
      operationId: accept
      parameters:
        - name: usersJSON
          in: body
          required: true
          description: JSON con los usuarios de la solicitud
          schema:
            type: array
            items:
              $ref: "#/definitions/RequestInput"
      responses:
        '200':
          description: Ok
        '400':
            description: Invalid Params
        '500':
          description: Internal Server Error
          
  /reject:
    put:
      summary: Rechazar una solicitud
      operationId: reject
      parameters:
        - name: usersJSON
          in: body
          required: true
          description: JSON con los usuarios de la solicitud
          schema:
            type: array
            items:
              $ref: "#/definitions/RequestInput"
      responses:
        '200':
          description: Ok
        '400':
            description: Invalid Params
        '500':
          description: Internal Server Error

  /erase:
    delete:
      summary: Borrar una solicitud
      operationId: erase
      parameters:
        - name: usersJSON
          in: body
          required: true
          description: JSON con los usuarios de la solicitud
          schema:
            type: array
            items:
              $ref: "#/definitions/RequestInput"
      responses:
        '200':
          description: Ok
        '400':
            description: Invalid Params
        '500':
          description: Internal Server Error
    
  
definitions:

  Request:
    type: object
    properties:
      id:
        type: integer
      user_origin:
        type: string
      user_destination:
        type: string
      status:
        type: string
      send_date:
        type: string
        format: date
    
  RequestInput:
    type: object
    properties:
      user_origin:
        type: string
      user_destination:
        type: string
      token:
        type: string
        
  RequestGetInput:
    type: object
    properties:
      user:
        type: string
      token:
        type: string
      
