swagger: '2.0'
info:
  version: 1.0.0
  title: gatherme-requests-ms
  description: "Microservicio para Solicitudes\n 
    Python + SQLite"
  license:
    name: Proyecto Gatherme, Software Architecture, 2020-I
  
    
host: localhost:5000
basePath: /requests
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
  
  
paths:
  /requests:
  
    post:
      summary: Crear una nueva solicitud de Gather
      operationId: createSol
      parameters:
        - name: usersJSON
          in: body
          required: true
          description: JSON con los usuarios de la solicitud
          schema:
            type: array
            items:
              $ref: "#/definitions/Request"
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

    get:
      summary: Retorna todas las solicitudes guardadas
      operationId: listSol
      responses:
        '200':
          description: Ok
        '500':
          description: Internal Server Error

    put:
      summary: Aceptar una solicitud
      operationId: acceptSol
      parameters:
        - name: usersJSON
          in: body
          required: true
          description: JSON con los usuarios de la solicitud
          schema:
            type: array
            items:
              $ref: "#/definitions/Request"
      responses:
        '200':
          description: Ok
        '400':
            description: Invalid Params
        '500':
          description: Internal Server Error

    delete:
      summary: Borrar una solicitud
      operationId: eraseSol
      parameters:
        - name: usersJSON
          in: body
          required: true
          description: JSON con los usuarios de la solicitud
          schema:
            type: array
            items:
              $ref: "#/definitions/Request"
      responses:
        '200':
          description: Ok
        '400':
            description: Invalid Params
        '500':
          description: Internal Server Error
    
  
definitions:
  Request:
    type: object
    properties:
      id:
        type: integer
      user_origin:
        type: string
      user_destination:
        type: string
      is_accepted:
        type: boolean
        default: false
      send_date:
        type: string
        format: date-time
